export const products = [
  {
    id: '1',
    name: 'Name Of Product',
    gallery: ['1', '7', '3', '9'],
    stars: 3,
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#9be8de', '#621ce1', '#c369ff', '#b6ea90'],
    panoramic: true,
  },
  {
    id: '2',
    name: 'at deleniti',
    gallery: ['2', '8', '4', '10'],
    stars: 5,
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#f969f9', '#1d70f4', '#d4ccd8', '#ecd7ce'],
    panoramic: true,
  },
  {
    id: '3',
    name: 'facere illum',
    gallery: ['3', '9', '5', '1'],
    price: 90,
    stars: 1,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#dcf4ad', '#90e90c', '#227aea', '#fcdffc'],
    panoramic: true,
  },
  {
    id: '4',
    name: 'eligendi',
    gallery: ['4', '10', '6', '2'],
    stars: 4,
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#caabe4', '#dbf0b0', '#a5c482', '#1f1ed1'],
    panoramic: true,
  },
  {
    id: '5',
    name: 'officiis nisi',
    gallery: ['5', '1', '7', '3'],
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#4d29fe', '#b1a071', '#fbea87', '#1877af'],
    panoramic: true,
  },
  {
    id: '6',
    name: 'veritatis amet',
    gallery: ['6', '2', '8', '4'],
    price: 90,
    discount_price: 50,
    stars: 4,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#ca9fed', '#b92f0d', '#33bcf4', '#3201bc'],
    panoramic: true,
  },
]
