
export const products = [
  {
    id: '1',
    name: 'Name Of Product',
    gallery: [
      'https://picsum.photos/seed/lXamB/640/480',
      'https://picsum.photos/seed/pA288/640/480',
      'https://picsum.photos/seed/ZFssDfW/640/480',
      'https://picsum.photos/seed/tkAEbi9/640/480',
    ],
    stars: 3,
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#9be8de', '#621ce1', '#c369ff', '#b6ea90'],
    panoramic: true,
  },
  {
    id: '2',
    name: 'at deleniti',
    gallery: [
      'https://picsum.photos/seed/cdoz9A9Q/640/480',
      'https://picsum.photos/seed/uk1tNUN8tO/640/480',
      'https://picsum.photos/seed/UA79mx/640/480',
      'https://picsum.photos/seed/l8a53LNX/640/480',
    ],
    stars: 5,
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#f969f9', '#1d70f4', '#d4ccd8', '#ecd7ce'],
    panoramic: true,
  },
  {
    id: '3',
    name: 'facere illum',
    gallery: [
      'https://picsum.photos/seed/EPAaJ/640/480',
      'https://picsum.photos/seed/OJy1255/640/480',
      'https://picsum.photos/seed/DoP4b/640/480',
      'https://picsum.photos/seed/gnRYUl/640/480',
    ],
    price: 90,
    stars: 1,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#dcf4ad', '#90e90c', '#227aea', '#fcdffc'],
    panoramic: true,
  },
  {
    id: '4',
    name: 'eligendi',
    gallery: [
      'https://picsum.photos/seed/3hu5cCca/640/480',
      'https://picsum.photos/seed/ZWCuNxgVR/640/480',
      'https://picsum.photos/seed/F5DcMz/640/480',
      'https://picsum.photos/seed/rhYYPJLU/640/480',
    ],
    stars: 4,
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#caabe4', '#dbf0b0', '#a5c482', '#1f1ed1'],
    panoramic: true,
  },
  {
    id: '5',
    name: 'officiis nisi',
    gallery: [
      'https://picsum.photos/seed/ww8yFxs/640/480',
      'https://picsum.photos/seed/D1BatSmyLP/640/480',
      'https://picsum.photos/seed/je22F4/640/480',
      'https://picsum.photos/seed/phExBz5/640/480',
    ],
    price: 90,
    discount_price: 50,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#4d29fe', '#b1a071', '#fbea87', '#1877af'],
    panoramic: true,
  },
  {
    id: '6',
    name: 'veritatis amet',
    gallery: [
      'https://picsum.photos/seed/7xNiLO0ZeR/640/480',
      'https://picsum.photos/seed/UzRF1wEE8t/640/480',
      'https://picsum.photos/seed/kdxHVFef/640/480',
      'https://picsum.photos/seed/tL2we9d/640/480',
    ],
    price: 90,
    discount_price: 50,
    stars: 4,
    describtion:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley",
    sizes: ['2*3 M', '4*4 M', '3*4 M'],
    colors: ['#ca9fed', '#b92f0d', '#33bcf4', '#3201bc'],
    panoramic: true,
  },
]
